package com.xtdar.app.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xtdar.app.db.DownloadGame;

import com.xtdar.app.db.DownloadGameDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadGameDaoConfig;

    private final DownloadGameDao downloadGameDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadGameDaoConfig = daoConfigMap.get(DownloadGameDao.class).clone();
        downloadGameDaoConfig.initIdentityScope(type);

        downloadGameDao = new DownloadGameDao(downloadGameDaoConfig, this);

        registerDao(DownloadGame.class, downloadGameDao);
    }
    
    public void clear() {
        downloadGameDaoConfig.getIdentityScope().clear();
    }

    public DownloadGameDao getDownloadGameDao() {
        return downloadGameDao;
    }

}
