package com.xtdar.app.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOWNLOAD_GAME.
 */
public class DownloadGame {

    private Long id;
    private int GameId;
    private String GameName;
    private String GameVersion;

    public DownloadGame() {
    }

    public DownloadGame(Long id) {
        this.id = id;
    }

    public DownloadGame(Long id, int GameId, String GameName, String GameVersion) {
        this.id = id;
        this.GameId = GameId;
        this.GameName = GameName;
        this.GameVersion = GameVersion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getGameId() {
        return GameId;
    }

    public void setGameId(int GameId) {
        this.GameId = GameId;
    }

    public String getGameName() {
        return GameName;
    }

    public void setGameName(String GameName) {
        this.GameName = GameName;
    }

    public String getGameVersion() {
        return GameVersion;
    }

    public void setGameVersion(String GameVersion) {
        this.GameVersion = GameVersion;
    }

}
